#!/usr/bin/env node

var events = require('events')
var util = require('util')

/**
 * Mock https.serverResponse
 * @type {Object}
 */
var mockResponse
var Eventer = function(){
	events.EventEmitter.call(this)

	this.data = ''
	this.count = 0

	this.onData = function(){

		//ensure data is only emitted once
		this.count++
		if(this.count<2)
			this.emit('data', this.data)
	}

	this.setEncoding = function(){

	}

	this.onEnd = function(){

		if(typeof this.data!='string')
			this.data = JSON.stringify(this.data)

		this.emit('end')
		this.data = ''
		//this.count = 0
	}

	this.run = function(){
		this.onData()
		this.onEnd()
	}
}
util.inherits(Eventer, events.EventEmitter)

var _ = {

	getMock: function(){
		return new Eventer()
	}
}

module.exports = _